name: ruler_picker_lib
description: "ruler picker"
version: 0.0.1
homepage: "https://github.com/icecrao2/moon_ruler_picker"
publisher: "icecrao3@gmail.com"
repository: "https://github.com/icecrao2/moon_ruler_picker"

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
